# Exemplo de Lista
frutas = ["Acerola", "Banana"]
print(frutas[0])
frutas.append("caju") #Adicona valor no final do vetor
print(frutas)
frutas [2] = "Maça"
print(frutas)

# Exemplo de Lista
nums = [3,1,4]
nums2 = (11,15,19)
nums.append(5)
print ("Append: ", nums)
nums.insert(3,8)
print ("Insert: ", nums)
nums.remove(4)
print ("Remove: ", nums)
nums.pop()
print ("Pop: ", nums)
nums.sort()
print ("Sort: ", nums)
nums.count(1)
print ("count: ", nums)
nums.reverse()
print ("Reverse: ", nums)
nums.copy()
print ("Copy: ", nums)
nums.extend(nums2)
print ("Extend: ", nums)
print (f"Tamanho da lista: {len(nums)}")
nums.clear()
print ("Clear: ", nums)
#nums.index()
#print ("Index: ", nums)
#nums.concatenar()
#print ("Concatenar : ", nums)
#nums.repetir()
#print ("repetir: ", nums)
#nums.Fatiamento()
#print ("Fatiamento: ", nums)